### ISSUE TITLE
Fails if there is no migrations table yet

### ISSUE THREAD

**Issue by deevus** [erjanmx/laravel-migrate-check#5]
We were using `php artisan migrate:status` for testing (local and CI) and for CI the database is always empty to begin with. I was happy to migrate to `migrate:check` but it throws an exception when no migrations have been run and the migrations table doesn't exist. 

```
In Connection.php line 664:
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '****.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)
In PDOConnection.php line 82:
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '****.migrations' doesn't exist
In PDOConnection.php line 80:
  SQLSTATE[42S02]: Base table or view not found: 1146 Table '****.migrations' doesn't exist
```

**Comment by erjanmx** [comment]
Hi @deevus, thanks for the issue.

What kind of behaviour do you expect from `migrate:check` command in terms of exit code in this case? Whether it should exit with non-zero code and say that there are actually migrations to run (like `php artisan migrate --pretend` does) or exit with zero code and say that there are no pending migrations (like `php artisan migrate:status` does)

**Comment by deevus** [comment]
I think I would expect it to exit with a non-zero code, if there are migrations to be run, regardless of whether the migrations table exists or not.

**Comment by erjanmx** [comment]
The new version (v1.2.0) that fixes your issue and few more things is released.

**Comment by deevus** [comment]
Confirmed fixed
