### ISSUE TITLE
Undefined command migrate:check when using Artisan::call

### ISSUE THREAD

**Issue by joaquinwojcik** [erjanmx/laravel-migrate-check#7]
Hello!

I recently installed this library. The **migrate:check** command works correctly in the console, but when I run it from Laravel using **Artisan: call**, it returns the following error:

`Symfony \ Component \ Console \ Exception \ CommandNotFoundException
Command "migrate:check" is not defined. Did you mean one of these? migrate migrate:fresh migrate:install migrate:refresh migrate:reset migrate:rollback migrate:status`

This is the code:

`public function CheckMigrations() {
return Artisan::call('migrate:check');
}`

**Comment by erjanmx** [comment]
Thanks @joaquinwojcik, will check and solve it

**Comment by joaquinwojcik** [comment]
I've found a fix!

In **MigrateCheckServiceProvider.php:**

Change this: 

`public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                MigrateCheckCommand::class,
            ]);
        }
    }`

To: 

`public function boot() { $this->commands([ MigrateCheckCommand::class, ]); }`

**Comment by erjanmx** [comment]
Hi, @joaquinwojcik, please check the new v1.2.1 version

**Comment by joaquinwojcik** [comment]
Awesome!! Thanks!

I'll close the issue
